version: "3.5"


services:
  my_web_app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "80"
    command: gunicorn web_app:app --bind 0.0.0.0:80 --reload
    volumes:
      - .:/app
    #python web_app.py

  web_server:
    build: ./nginx
    # image: nginx
    ports:
      - "8082:80"
    depends_on:
        - my_web_app
